### ISSUE TITLE
Problem bindingu

### ISSUE THREAD

**Issue by legier** [LukasCwaj/MVVM_Calculator#1]
Nie działa Ci to dlatego, że w linicje 99 w MainWindow.xaml bindujesz tekst do Calculation.Result, tylko problem jest taki, że widok nie jest wstanie zapisać się do notyfikacji zagnieżdżonych. Widok może zapisać się do notyfikacji tylko w model widoku - CalculatorViewModel. W takim wypadku Twój model widoku musiałby się zapisać w modelu na notyfikacje od wyniku i forwardować tę notyfikację dalej.
Inny problem jaki widzę, to masz trochę złą hierarchię. W tej aplikacji Twój model jedyne co robi to przechowuje zmienne, a przecież powinien implementować całą logikę kalkulatora. Kalkulator też nie musi implementować INotifyPropertyChanged. Ten interfejs służy tylko temu, aby poinformować widok, że w modelu widoku zmieniła się jakaś właściwość.
Widziałbym to tak:
ViewModel właściwości:
FirstValue, SecondValue, Result (tylko dla Result wołasz OnPropertyChanged, bo pozostałę zmienne się przecież nie zmieniają, jeśli użytkownich ich nie zmieni)
Zestaw komend, których Execute jest podpięte do metody, która zawoła odpowiednią metodę z klakulatora, poda jej input i wpisze output do Result (tym samym wołając OnPropertyChanged)

Jeżeli koniecznie chcesz w kalkulatorze trzymać wejście i wynik, to binding dla wejść możesz pozostawić bez zmian (ale wywalić OnPropertyChanged), a gdy komenda wywoła odpowiednią metodę kalkulatora i zupdatuje mu się wynik, to w ViewModel zawołać OnPropertyChanged("Result")

**Comment by LukasCwaj** [comment]
Dziękuję serdecznie za pomoc, myślę że teraz uda się doprowadzić to do poprawnego działania. Dziękuję jeszcze raz :)

**Comment by LukasCwaj** [comment]
gdym tylko mógł mieć pytanie: właściwości w ViewModel powinny odnosić się do tych zdefiniowanych w Modelu ?
w taki sposób ?

**Comment by LukasCwaj** [comment]
private Calculator calculation;

        public Calculator Calculation
        {
            get { return calculation; }
            set { calculation = value; NotifyPropertyChanged("Calculation"); }
        }

        public double Calculation1
        {
            get { return calculation.FirstValue; }
            set { calculation.FirstValue = value; }
        }

**Comment by legier** [comment]
Tak, w taki sposób.
Aczkolwiek nie mogę Ci powiedzieć, że tak jest zawsze, bo przy skomplikowanych widokach czy modelach to różnie tam wygląda.

**Comment by legier** [comment]
Ogólnie w tym wzorcu projektowym chodzi o to, że widok ma nie mieć pojęcia czym jest model i jedyne z kim się komunikuje to model widoku. A model widoku implementuje interakcje pomiędzy tymi dwoma. Tak samo model nie ma pojęcia jaki jest widok. Implementuje samą funkcjonalność i udostępnia jakieś rzeczy, na które sobie patrzy model widoku i przekazuje je dalej.

**Comment by LukasCwaj** [comment]
Kurczę chyba coś źle zrozumiałem albo coś robię źle
dodałem analogicznie jak pierwsza wartość tą drugą i wynik : 

public double Calculation2
        {
            get { return Calculation.SecondValue; }
            set { Calculation.SecondValue = value; }
        }

        public double Calculation3
        {
            get { return Calculation.Result; }
            set { Calculation.Result = value; NotifyPropertyChanged("Result"); }
        }

w kalkulatorze tak jak mówiłeś dodałem prostą funkcję do obliczania:

public double Addition (double x, double y)
        {
            return x + y;
        }

i w ViewModel wywolanie:

   private void AddExecute(object parameter)
        {
            Calculation3 = calculation.Addition(Calculation1, Calculation2);
        }

i chyba nadal robię ten sam błąd bo pierwsza i druga wartość przepisują się poprawnie a do wyniku i tak nie trafia to co powinno....

**Comment by LukasCwaj** [comment]
no właśnie wydawało mi się, że w miarę to rozumiem, że tak ma być to wszystko rozdzielone, ale jakoś nie chce się to kleić w całość ...

**Comment by legier** [comment]
Teraz pytanie jak podpinasz widok. Czy podpiąłeś go do Calculation1 2 3? Jeśli tak, to zobacz, że w Calculation3 powiadamiasz o zmianie właściwości Result, a nie Calculation3

**Comment by LukasCwaj** [comment]
no tak.... racja .... aż mi głupio za taki błąd. Dziękuję bardzo - działa ! :D 
Dziękuję jeszcze raz i przepraszam za problem i pewnie głupie pytania :D
Dziękuję

**Comment by legier** [comment]
To nie był żaden problem.
Nie ma głupich pytań, gdy się czegoś uczysz i idziesz do przodu. ;)
